name: ran-rl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.14
  - pip
  - numpy=2.4.1
  - pandas=3.0.0
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - ipykernel=7.1.0
  - jupyter=1.1.1
  - tqdm=4.67.3
  - tensorboard=2.20.0
  - gymnasium=1.0.0
  - stable-baselines3=2.9.0
  - pip:
    - d3rlpy==2.8.1
    - torch==2.12.1
    - torchaudio==2.5.1
    - torchvision==0.20.1