"""
Trains a QR-CQL policy on the offline
dataset generated by generate_dataset.py.

QR-CQL combines CQL's conservatism penalty with a distributional
(quantile regression) Q-function instead of a scalar mean Q-function.
This lets the policy reason about the full return distribution rather
than just its expectation, which the wireless RRM literature shows
improves risk-sensitivity over both DQN and plain CQL.

d3rlpy implements this as DiscreteCQL configured with a
QRQFunctionFactory Q-function — CQL's existing conservatism loss
(alpha * logsumexp penalty) automatically applies over the quantile
distribution once the Q-function is swapped, giving exactly the QR-CQL
formulation (CQL penalty + QR-DQN loss) with no custom training loop.

Usage:
    python generate_dataset.py   # first (same dataset as CQL)
    python train_qr_cql.py          # then this

Output:
    models/qr_cql_policy  — saved d3rlpy policy (directory)
"""

import os
import numpy as np
import torch
import random
import numpy as np
import d3rlpy

DATASET_PATH = "dataset/offline_dataset.h5"
MODEL_SAVE_DIR = "models/qr_cql_policy"
N_STEPS = 250_000   # match CQL/DQN for fair comparison
N_QUANTILES = 32     # standard QR-DQN default; matches d3rlpy default

torch.manual_seed(42)
np.random.seed(42)
random.seed(42)
d3rlpy.seed(42)


def main():
    os.makedirs("models", exist_ok=True)

    # Load d3rlpy
    try:
        import d3rlpy
        from d3rlpy.algos import DiscreteCQLConfig
        from d3rlpy.models import QRQFunctionFactory
        d3rlpy.seed(42)

    except ImportError:
        raise ImportError(
            "d3rlpy not installed. Run: pip install d3rlpy"
        )

    # Load dataset — identical to CQL, same offline data
    print(f"Loading dataset from {DATASET_PATH}...")
    import d3rlpy as d3
    with open(DATASET_PATH, "rb") as f:
        dataset = d3.dataset.ReplayBuffer.load(f, d3.dataset.InfiniteBuffer())

    print(f"Dataset loaded:")
    print(f"  Transitions : {len(dataset.episodes)}")
    print(f"  Episodes    : {len(dataset.episodes)}")
    print(f"  Transitions : {sum(len(ep) for ep in dataset.episodes)}")

    from d3rlpy.algos import DiscreteCQLConfig
    from d3rlpy.models import QRQFunctionFactory

    q_func = QRQFunctionFactory(n_quantiles=N_QUANTILES)

    qr_cql = DiscreteCQLConfig(
        learning_rate=2.5e-5,
        batch_size=32,
        gamma=0.99,
        target_update_interval=8000,
        alpha=0.3,               # same conservatism weight as your CQL run
        q_func_factory=q_func,   # ← the only structural change vs train_cql.py
    ).create(device="cpu")

    # Train
    print(f"\nTraining QR-CQL for {N_STEPS:,} steps on offline dataset...")
    print(f"(Quantile regression Q-function, {N_QUANTILES} quantiles, "
          f"CQL conservatism penalty applied over the distribution)\n")

    qr_cql.fit(
        dataset,
        n_steps=N_STEPS,
        n_steps_per_epoch=10_000,
        save_interval=10,
        evaluators={},   # no online evaluation — offline only
        experiment_name="QR-CQL_run",
    )

    # Save
    qr_cql.save(MODEL_SAVE_DIR)
    print(f"\nQR-CQL policy saved → {MODEL_SAVE_DIR}")
    print("Next: python main.py --policy qr_cql --split eval")

if __name__ == "__main__":
    main()