"""
Trains an IQL (Implicit Q-Learning) policy on the offline dataset generated by generate_dataset.py.
Uses d3rlpy's continuous IQL implementation with a proxy continuous-action mapping layer.

Usage:
    python generate_dataset.py   # first
    python train_iql.py          # then this
Output:
    models/iql_policy  — saved d3rlpy policy (directory)
"""
import os
import random
import numpy as np
import torch
import d3rlpy
from d3rlpy.algos import IQLConfig

DATASET_PATH = "dataset/offline_dataset.h5"
MODEL_SAVE_DIR = "models/iql_policy"
N_STEPS = 200_000

# Set determinism
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)
d3rlpy.seed(42)

def main():
    os.makedirs("models", exist_ok=True)

    # Load dataset using ReplayBuffer structure
    print(f"Loading dataset from {DATASET_PATH}...")
    with open(DATASET_PATH, "rb") as f:
        loaded_buffer = d3rlpy.dataset.ReplayBuffer.load(f, d3rlpy.dataset.InfiniteBuffer())
    
    print(f"Dataset loaded. Converting to continuous proxy MDPDataset...")
    
    all_obs, all_actions, all_rewards, all_terminals = [], [], [], []
    for episode in loaded_buffer.episodes:
        all_obs.append(episode.observations)
        all_rewards.append(episode.rewards)
        terminals_array = np.zeros(len(episode.observations), dtype=np.float32)
        if episode.terminated:
            terminals_array[-1] = 1.0  # Set terminal flag on the last transition
        all_terminals.append(terminals_array)
        
        # Continuous Proxy Action Mapping (1 -> -1.0, 0 -> 1.0)
        continuous_actions = np.where(episode.actions == 1.0, -1.0, 1.0).astype(np.float32)
        if len(continuous_actions.shape) == 1:
            continuous_actions = np.expand_dims(continuous_actions, axis=-1)
        all_actions.append(continuous_actions)
        
    dataset = d3rlpy.dataset.MDPDataset(
        observations=np.concatenate(all_obs, axis=0),
        actions=np.concatenate(all_actions, axis=0),
        rewards=np.concatenate(all_rewards, axis=0),
        terminals=np.concatenate(all_terminals, axis=0),
        action_space=d3rlpy.constants.ActionSpace.CONTINUOUS
    )
    
    print(f"Dataset reconstruction complete.")
    print(f"  Episodes    : {len(dataset.episodes)}")
    print(f"  Transitions : {sum(len(ep) for ep in dataset.episodes)}")
    print("Action space translation complete! Dataset is ready for continuous standard IQL.")

    iql = IQLConfig(
        actor_learning_rate=6.25e-5,
        critic_learning_rate=6.25e-5,
        batch_size=32,
        gamma=0.99,
        expectile=0.9,     
        weight_temp=2.0,   
    ).create(device="cpu")
    # Train
    print(f"\nTraining IQL for {N_STEPS:,} steps on offline dataset...")
    print("(No environment interaction — pure offline RL)\n")
    
    iql.fit(
        dataset,
        n_steps=N_STEPS,
        n_steps_per_epoch=10_000,
        evaluators={},   # no online evaluation — offline only
    )

    # Save
    iql.save(MODEL_SAVE_DIR)
    print(f"\nIQL policy saved → {MODEL_SAVE_DIR}")
    print("Next: python main.py --policy iql --split eval")

if __name__ == "__main__":
    main()