"""
Trains an CQL (Implicit Q-Learning) policy on the offline dataset
generated by generate_CQN_dataset.py.

CQL (Kostrikov et al. 2021) is an offline RL algorithm that learns
purely from a fixed dataset without any environment interaction.
This is the primary contribution of the thesis — first application
of offline RL to the Cell Switch-Off problem.

Uses d3rlpy's CQL implementation.

Usage:
    python generate_CQN_dataset.py   # first
    python train_cql.py          # then this

Output:
    models/cql_policy  — saved d3rlpy policy (directory)
"""

import os
import numpy as np
import torch
import random
import numpy as np
import d3rlpy

DATASET_PATH = "dataset/offline_dataset.h5"
MODEL_SAVE_DIR = "models/cql_policy"
N_STEPS = 200_000   # training steps — match DQN for fair comparison

torch.manual_seed(42)
np.random.seed(42)
random.seed(42)
d3rlpy.seed(42)


def main():
    os.makedirs("models", exist_ok=True)

    # Load d3rlpy
    try:
        import d3rlpy
        from d3rlpy.algos import DiscreteCQLConfig
        d3rlpy.seed(42)

    except ImportError:
        raise ImportError(
            "d3rlpy not installed. Run: pip install d3rlpy"
        )

    # Load dataset
    print(f"Loading dataset from {DATASET_PATH}...")
    import d3rlpy as d3
    with open(DATASET_PATH, "rb") as f:
        dataset = d3.dataset.ReplayBuffer.load(f, d3.dataset.InfiniteBuffer())

    print(f"Dataset loaded:")
    print(f"  Transitions : {len(dataset.episodes)}")
    print(f"  Episodes    : {len(dataset.episodes)}")
    print(f"  Transitions : {sum(len(ep) for ep in dataset.episodes)}")

    from d3rlpy.algos import DiscreteCQLConfig
    cql = DiscreteCQLConfig(
        learning_rate=6.25e-5,
        batch_size=32,
        gamma=0.99,
        target_update_interval=8000,
        alpha=0.2,
    ).create(device="cpu")

    # Train
    print(f"\nTraining CQL for {N_STEPS:,} steps on offline dataset...")
    print("(No environment interaction — pure offline RL)\n")

    cql.fit(
        dataset,
        n_steps=N_STEPS,
        n_steps_per_epoch=10_000,
        evaluators={},   # no online evaluation — offline only
    )

    # Save
    cql.save(MODEL_SAVE_DIR)
    print(f"\nCQL policy saved → {MODEL_SAVE_DIR}")
    print("Next: python main.py --policy cql --split eval")

if __name__ == "__main__":
    main()